@CourseWebApiProject_HostAddress = http://localhost:5109
@id = 00000000-0000-0000-0000-000000000000
@title = TEST
@from = 2026-08-01
@to = 2026-08-31
@page = 1
@pageSize = 3

### Get all events
GET {{CourseWebApiProject_HostAddress}}/events/
Accept: application/json

### Get events by query
GET {{CourseWebApiProject_HostAddress}}/events?title={{title}}&from={{from}}&to={{to}}
Content-Type: application/json

### Get events by page
GET {{CourseWebApiProject_HostAddress}}/events?page={{page}}&pageSize={{pageSize}}
Content-Type: application/json

### Get event by id
GET {{CourseWebApiProject_HostAddress}}/events/{{id}}
Accept: application/json

### Create event
POST {{CourseWebApiProject_HostAddress}}/events
Content-Type: application/json
{
  "title": "test event",
  "description": "",
  "startAt": "2026-08-12T00:00:00",
  "endAt": "2026-08-13T00:00:00"
}

### Update event
PUT {{CourseWebApiProject_HostAddress}}/events/{{id}}
Content-Type: application/json
{
  "title": "updated test event",
  "description": "updated description",
  "startAt": "2027-01-01T00:00:00",
  "endAt": "2027-01-01T00:01:00"
}

### Delete event
DELETE {{CourseWebApiProject_HostAddress}}/events/{{id}}
Accept: application/json

###
